// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlarmSubscriptionController from "./alarm_subscription_controller"
application.register("alarm-subscription", AlarmSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
